apiVersion: v1
data:
  username: cm9vdA==
kind: Secret
metadata:
  name: mysql-user
  namespace: blog
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-db
  namespace: blog
spec:
  replicas: 1
  selector:
     matchLabels:
       app: wp-db
  template:
    metadata:
      labels:
        app: wp-db
    spec:
      containers:
      - name: wp-db
        image: mysql:8.0.0
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "{aqua.mysql.password}"
        ports:
          - containerPort: 3306
        readinessProbe:
            exec:
              command:
              - stat
              - /var/run/mysqld/mysqld.sock
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 2
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: wp-db
  namespace: blog
  labels:
    app: wp-db
spec:
  ports:
    - port: 3306
  selector:
    app: wp-db
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-server
  namespace: blog
spec:
  replicas: 0
  selector:
     matchLabels:
       app: wp-server
  template:
    metadata:
      labels:
        app: wp-server
    spec:
      imagePullSecrets:
      - name: aqua-demo
      containers:
      - name: wp-server
        image: aquademo.azurecr.io/wordpress:plugins
        env:
        - name: "WORDPRESS_DB_HOST"
          value: "wp-db"
        - name: "WORDPRESS_DB_USER"
          valueFrom:
            secretKeyRef:
              name: "mysql-user"
              key: "username"
        - name: "WORDPRESS_DB_PASSWORD"
          value: "{aqua.mysql.password}"
        ports:
          - containerPort: 80
        readinessProbe:
            httpGet:
              path: /wp-admin/
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 2
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: wp-server
  namespace: blog
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wp-server
  type: LoadBalancer
