apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-with-sys-admin
spec:
  containers:
  - name: ubuntu-with-sys-admin
    image: ubuntu:latest
    securityContext:
      capabilities:
        add: ["SYS_ADMIN"]
    command:
      - sleep
      - infinity
