apiVersion: v1
kind: Namespace
metadata:
  name: go-docker
---
apiVersion: v1
kind: Service
metadata:
  name: go-docker-svc
  namespace: go-docker
  labels:
    app: go-docker
spec:
  ports:
    - port: 8081
  selector:
    app: go-docker
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-docker
  namespace: go-docker
spec:
  replicas: 1
  selector:
     matchLabels:
       app: go-docker
  template:
    metadata:
      labels:
        app: go-docker
    spec:
      containers:
      - name: go-docker
        image: dstubked/go-docker:1
        env:
        - name: "AQUA_PROFILE"
          value: "true"
        ports:
          - containerPort: 8081
