apiVersion: apps/v1
kind: Deployment
metadata:
  name: infected-pod
spec:
  selector:
    matchLabels:
      app: infected-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: infected-pod
    spec:
      containers:
      - name: infected-pod
        image: tsstesting/nssolutions:no-api-key
        command:
          - sleep
          - infinity
        volumeMounts:
          - name: var-tmp
            mountPath: /var/tmp
      volumes:
      - name: var-tmp
        hostPath:
          path: /var/tmp
