apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: aqua-nginx-deployment
spec:
  selector:
    matchLabels:
      app: aqua-nginx
  replicas: 2 
  template:
    metadata:
      labels:
        app: aqua-nginx
    spec:
      containers:
      - name: aqua-nginx
        image: nginx:1.7.1
        env:
          - name: TEST_A
            value: "TEST_A_Value"
          - name: TEST_B
            value: "TEST_B_Value"
          - name: MYSQL_PASS
            value: "{aqua.mysql.pass}"
          - name: AQUA_PROFILE
            value: "true"
        ports:
        - containerPort: 80
