apiVersion: v1
kind: Service
metadata:
  name: nginx-front-end
  namespace: front-end
  labels:
    app: aqua-nginx
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
      name: aqua-nginx
  selector:
    app: aqua-nginx
  type: LoadBalancer
