apiVersion: v1
kind: Service
metadata:
  name: aqua-db
  namespace: aqua
  labels:
    app: aqua-db
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      name: aqua-db
  selector:
    app: aqua-db
  type: NodePort
