apiVersion: v1
kind: Namespace
metadata:
  name: blog
---
apiVersion: v1
data:
  username: cm9vdA==
kind: Secret
metadata:
  name: mysql-user
  namespace: blog
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-db
  namespace: blog
spec:
  replicas: 1
  selector:
     matchLabels:
       app: wp-db
  template:
    metadata:
      labels:
        app: wp-db
    spec:
      containers:
      - name: wp-db
        image: docker.io/mysql:8.0.15
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "{aqua.mysql.password}"
        ports:
          - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: wp-db
  namespace: blog
  labels:
    app: wp-db
spec:
  ports:
    - port: 3306
  selector:
    app: wp-db
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: wp-server
  namespace: blog
  labels:
    app: wp-server
spec:
  ports:
    - port: 80
  selector:
    app: wp-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-server
  namespace: blog
spec:
  replicas: 1
  selector:
     matchLabels:
       app: wp-server
  template:
    metadata:
      labels:
        app: wp-server
    spec:
      containers:
      - name: wp-server
        image: docker.io/wordpress:php7.3-apache
        env:
        - name: "WORDPRESS_DB_HOST"
          value: "wp-db"
        - name: "WORDPRESS_DB_USER"
          valueFrom:
            secretKeyRef:
              name: "mysql-user"
              key: "username"
        - name: "WORDPRESS_DB_PASSWORD"
          value: "{aqua.mysql.password}"
        ports:
          - containerPort: 80
